USE [master]
GO
/****** Object:  Database [Assignment3]    Script Date: 2022/05/26 14:17:33 ******/
CREATE DATABASE [Assignment3]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Assignment3', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Assignment3.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Assignment3_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Assignment3_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Assignment3] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Assignment3].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Assignment3] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Assignment3] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Assignment3] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Assignment3] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Assignment3] SET ARITHABORT OFF 
GO
ALTER DATABASE [Assignment3] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Assignment3] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Assignment3] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Assignment3] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Assignment3] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Assignment3] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Assignment3] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Assignment3] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Assignment3] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Assignment3] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Assignment3] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Assignment3] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Assignment3] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Assignment3] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Assignment3] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Assignment3] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Assignment3] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Assignment3] SET RECOVERY FULL 
GO
ALTER DATABASE [Assignment3] SET  MULTI_USER 
GO
ALTER DATABASE [Assignment3] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Assignment3] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Assignment3] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Assignment3] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [Assignment3] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Assignment3', N'ON'
GO
USE [Assignment3]
GO
/****** Object:  Table [dbo].[Brands]    Script Date: 2022/05/26 14:17:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Brands](
	[BrandId] [int] NOT NULL,
	[Name] [nvarchar](50) NULL,
	[Description] [nvarchar](max) NULL,
	[DateCreated] [datetime2](7) NULL,
	[DateModified] [datetime2](7) NULL,
	[IsActive] [bit] NULL,
	[IsDeleted] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[BrandId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Login]    Script Date: 2022/05/26 14:17:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Login](
	[userID] [int] IDENTITY(1,1) NOT NULL,
	[userName] [varchar](50) NOT NULL,
	[passWord] [varchar](200) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[userID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Products]    Script Date: 2022/05/26 14:17:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[ProductId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
	[Description] [varchar](max) NULL,
	[DateCreated] [datetime2](7) NULL,
	[DateModified] [datetime2](7) NULL,
	[IsActive] [bit] NULL,
	[IsDeleted] [bit] NULL,
	[Price] [decimal](18, 0) NULL,
	[ProductTypeId] [int] NULL,
	[BrandId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ProductId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProductTypes]    Script Date: 2022/05/26 14:17:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProductTypes](
	[ProductTypeId] [int] NOT NULL,
	[Name] [varchar](50) NULL,
	[Description] [varchar](max) NULL,
	[DateCreated] [datetime2](7) NULL,
	[DateModified] [datetime2](7) NULL,
	[IsActive] [bit] NULL,
	[IsDeleted] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[ProductTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Products]  WITH CHECK ADD FOREIGN KEY([BrandId])
REFERENCES [dbo].[Brands] ([BrandId])
GO
ALTER TABLE [dbo].[Products]  WITH CHECK ADD FOREIGN KEY([ProductTypeId])
REFERENCES [dbo].[ProductTypes] ([ProductTypeId])
GO
USE [master]
GO
ALTER DATABASE [Assignment3] SET  READ_WRITE 
GO
